app/code/crypto/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import include, path

from . import views
from .views import LikeView, FavCoinView

app_name = 'crypto'
urlpatterns = [
	path('', views.MyCryptoView.as_view(), name='index'),
	path('<int:cryptocurrency_id>/',views.DetailView.as_view(), name = 'detail'),
	#path('members/',include('django.contrib.auth.urls')),
	#path('members/',include('members.urls'))
	path('search_crypto/',views.SearchCryptoView.as_view(), name = 'search-cryptos'),
	path('add_post/', views.AddPostView.as_view(), name='add_post'),
	path('news/', views.PostView.as_view(), name='view_post'),
	path('news/<int:post_id>', views.PostDetail.as_view(), name='news_detail'),
	path('like/<int:pk>', LikeView, name='like_post'),
	path('fav/<int:pk>', FavCoinView, name='fav_coin'),
	path('news/<int:post_id>/comment/', views.AddCommentView.as_view(), name='add_comment'),	
	path('news/<int:post_id>/delete/', views.DeletePostView.as_view(), name='delete_post'),
	path('news/<int:post_id>/edit/', views.EditPostView.as_view(), name='edit_post'),
	path('exchange/', views.ExchangeView.as_view(), name='exchange'),
	path('sell/', views.SellCryptoView.as_view(), name='sell'),
	path('buy/', views.BuyCryptoView.as_view(), name='buy'),

]

app/code/predix/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from contact import views as contact_views



urlpatterns = [
    path('crypto/', include('crypto.urls')),
    path('admin/', admin.site.urls),
    path('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
    path('contact',contact_views.contact_view,name= 'contact')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/code/contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
	email = models.EmailField()
	subject = models.CharField(max_length=255)
	message = models.TextField()

	def __str__(self):
		return self.email

app/code/contact/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

app/code/contact/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render
from .forms import ContactForm


def contact_view(request):
    form = ContactForm()
    context = {'form': form}
    return render(request, 'contact/contact.html', context)

app/code/contact/templates/contact/contact.html
{% extends 'crypto/base.html' %}
{% load static %}

{% block content %}
<style>
input[type=text], input[type=email], textarea {
 width: 100%;
 padding: 12px 20px;
 margin: 8px 0;
 display: inline-block;
}
</style>
<form action="" method="post">
    <input type="hidden" name="csrfmiddlewaretoken" value="yTF5g7ceTgkwsOimKxZpuV10DG4a1TWFwQ60pneu047lPvu6kTAlNYPfYEC9G8jq">
    {% csrf_token %}
    <tr>
        <th>
            <label for="id_email">Email:</label>
        </th>
        <td>
            <input type="email" name="email" maxlength="254" required id="id_email">
        </td>
    </tr>
    <tr>
        <th>
            <label for="id_subject">Subject:</label>
        </th>
        <td>
            <input type="text" name="subject" maxlength="255" required id="id_subject">
        </td>
    </tr>
    <tr>
        <th>
            <label for="id_message">Message:</label>
        </th>
        <td>
            <textarea name="message" cols="40" rows="10" required id="id_message"></textarea>
        </td>
    </tr>
    <input type="submit" value="Submit">
</form>
{% endblock %}