app/code/crypto/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import include, path

from . import views
from .views import LikeView, FavCoinView

app_name = 'crypto'
urlpatterns = [
	path('', views.MyCryptoView.as_view(), name='index'),
	path('<int:cryptocurrency_id>/',views.DetailView.as_view(), name = 'detail'),
	#path('members/',include('django.contrib.auth.urls')),
	#path('members/',include('members.urls'))
	path('search_crypto/',views.SearchCryptoView.as_view(), name = 'search-cryptos'),
	path('add_post/', views.AddPostView.as_view(), name='add_post'),
	path('news/', views.PostView.as_view(), name='view_post'),
	path('news/<int:post_id>', views.PostDetail.as_view(), name='news_detail'),
	path('like/<int:pk>', LikeView, name='like_post'),
	path('fav/<int:pk>', FavCoinView, name='fav_coin'),
	path('news/<int:post_id>/comment/', views.AddCommentView.as_view(), name='add_comment'),	
	path('news/<int:post_id>/delete/', views.DeletePostView.as_view(), name='delete_post'),
	path('news/<int:post_id>/edit/', views.EditPostView.as_view(), name='edit_post'),
	path('exchange/', views.ExchangeView.as_view(), name='exchange'),
	path('sell/', views.SellCryptoView.as_view(), name='sell'),
	path('buy/', views.BuyCryptoView.as_view(), name='buy'),

]

app/code/members/urls.py
from django.urls import path
from .views import UserRegisterView, UserEditView, PasswordsChangeView, ShowProfilePageView, EditProfilePageView, CreateProfilePageView
#from django.contrib.auth import views as auth_views
from . import views
app_name = 'members'
urlpatterns = [
	path('register/', UserRegisterView.as_view(), name='register'),
	path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
	#path('password/', auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html')),
	path('password/', PasswordsChangeView.as_view(template_name='registration/change-password.html')),
	path('password_success', views.password_success, name="password_success"),
	path('<int:pk>/profile/', ShowProfilePageView.as_view(), name='show_profile_page'),
	path('<int:pk>/edit_profile_page/', EditProfilePageView.as_view(), name='edit_profile_page'),
	path('create_profile_page/', CreateProfilePageView.as_view(), name='create_profile_page'),
	path('',views.logoutPage, name = 'logoutPage'),
	path('login/', views.loginPage, name = 'loginPage'),
]

app/code/predix/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from contact import views as contact_views



urlpatterns = [
    path('crypto/', include('crypto.urls')),
    path('admin/', admin.site.urls),
    path('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
    path('contact',contact_views.contact_view,name= 'contact')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/code/crypto/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField



class Cryptocurrency(models.Model):
	rank = models.IntegerField()
	name = models.CharField(max_length = 100)
	symbol = models.CharField(max_length= 10)
	price =  models.FloatField()
	favs = models.ManyToManyField(User, related_name = 'crypto_cryptocurrency')
	def __str__(self):
		s = str(self.rank)+" "+self.name+" "+self.symbol+" "+str(self.price)
		return s

class CryptocurrencyLog(models.Model):
	name = models.CharField(max_length=100)
	current_time = models.DateTimeField()
	current_price = models.FloatField()
	cryptocurrency = models.ForeignKey(Cryptocurrency, null= True, on_delete = models.CASCADE)
	def __str__(self):
		s = self.name+"\t"+str(self.current_time)+"\t"+str(self.current_price)+"\n"
		return s

class Post(models.Model):
	title = models.CharField(max_length=255)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	body = RichTextField(blank=True, null = True)
	post_date = models.DateField(auto_now_add=True)
	likes = models.ManyToManyField(User, related_name='crypto_post')

	def __str__(self):
		return self.title + ' | ' + str(self.author)


class Profile(models.Model):
	user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, related_name="profile")
	bio = models.TextField()
	profile_pic = models.ImageField(null=True, blank=True, upload_to="profile/")
	website_url = models.CharField(max_length=255, null=True, blank=True)
	owned_dollar = models.FloatField(default=0)


	def __str__(self):
		return str(self.user)

class Entity(models.Model):
	user = models.ForeignKey(User, related_name='entities',on_delete=models.CASCADE)
	cryptocurrency = models.ForeignKey(Cryptocurrency, related_name='entities',on_delete=models.CASCADE)
	amount = models.FloatField(default=0)
	total = models.FloatField(default=0)


class Comment(models.Model):
	post = models.ForeignKey(Post,null= True,  on_delete=models.CASCADE)
	name = models.CharField(max_length=50)
	body = RichTextField(blank=True, null = True)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '%s - %s' % (self.name, self.body)

class Fav(models.Model):
	user = models.ForeignKey(User, related_name='favorites',on_delete=models.CASCADE)
	cryptocurrency = models.ForeignKey('Cryptocurrency', related_name='favorites',on_delete=models.CASCADE)

app/code/crypto/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, Comment
from django import forms

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','password1','password2']

		
class PostForm(ModelForm):
	class Meta:
		model = Post
		fields = ['title','author', 'body']

		widgets = {
			'title': forms.TextInput(attrs={'class': 'form-control'}),
			'author': forms.TextInput(attrs={'class': 'form-control', 'value':'', 'id':'elder', 'type':'hidden'}),
			'body': forms.Textarea(attrs={'class': 'form-control'}),			

		}
class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'body')

		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control'}),
			'body': forms.Textarea(attrs={'class': 'form-control'}),			
			
		}

app/code/crypto/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render, redirect
import json
from .models import Cryptocurrency, CryptocurrencyLog, Post, Profile, Comment, Fav, Entity
import logging
from django.utils import timezone
import requests
from datetime import timedelta
from django.views import View
from .forms import PostForm, CommentForm
from django.urls import reverse
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import JsonResponse
import numpy
from sklearn.linear_model import LinearRegression



class SearchCryptoView(View):
	def get(self, request):	
		searched = request.GET['searched']
		cryptos = Post.objects.filter(title__icontains=searched )

		return render(request,'crypto/search_cryptos.html',{'searched':searched,'cryptos':cryptos})
	def post(self, request):
		return render(request,'crypto/search_cryptos.html',{})



class MyCryptoView(View):
	def get(self, request):
		# TODO: Keep the cryptocurrency and the price in a map to track it later and save to the database
		# TODO: Send to predicted prices to the front-end to display
		# predicted = model.predict(test_data)
		# each feature a column = time
		# each coin a sample = a row
		## [a1,a2,a3,a4] coin a's price over time
		## [b1,b2,b3,b4] coin b's price over time
		## ...
		##
		X = []
		training_Y = []
		Maxs = []
		# Keep max of each coin to also normalize the Y
		# calculate X
		all_cryptos = Cryptocurrency.objects.order_by('rank')


		for crypto in all_cryptos:
			# will ignore the data if the historical data size is less that 25
			# will use last 25 data for training
			if 25>len(CryptocurrencyLog.objects.filter(cryptocurrency=crypto).values_list('current_price', flat=True)):
				continue
			coin_price_over_time = CryptocurrencyLog.objects.filter(cryptocurrency=crypto).order_by('-current_time').values_list('current_price', flat=True)[:25]
			coin_price_over_time = list(coin_price_over_time)
			# Normalization- from sklearn import preprocessing can be used too
			mx = max(coin_price_over_time)
			Maxs.append(mx)
			coin_price_over_time = [x / mx for x in coin_price_over_time]
			X.append(coin_price_over_time)
			# calculate Y
			training_Y.append(crypto.price)
		# found X, convert to numpy
		X = numpy.array(X)


		temp = []

		for i, v in enumerate(training_Y):
			temp.append(v/Maxs[i])
		training_Y = temp
		training_Y = numpy.array(training_Y)


		model = LinearRegression(normalize = True)
		#training using 25 coins
		training_Y.reshape(-1, 1)
		#print(training_Y.shape)
		#model.fit(X[:25], training_Y[:25])
		#Predict
		#predicted = model.predict(X[25:])
		#print("Predicted array is:", predicted, "\n\n######\n\nActual array is:",training_Y[25:])
		####################################################################################
		# Q:The result is between [0:1] should I multiply it by the max value to ge the correnct result?!
		####################################################################################
		# Denormalization
		result = []
		#print("------AFTER DENORMALIZATION-------")
		#for i,v in enumerate(predicted):
		#	result.append(v*Maxs[i])
		#	print(v, v*Maxs[i],"\n")

		#________________________________________
		coins = Cryptocurrency.objects.all()
		user=request.user
		if request.user.is_authenticated:
			interest = Fav.objects.filter(user=request.user)[:3]
			likes =Fav.objects.filter(user=request.user).values_list('cryptocurrency_id', flat=True)
		else:
			likes = []
			interest = []
		context = {
					'best_crypto_list': coins,
					'likes': likes,
					'interest': interest
					}
		return render(request, 'crypto/index.html', context)
	


class DetailView(View):
	def get(self, request, cryptocurrency_id):
		cryptocurrency = CryptocurrencyLog.objects.filter(cryptocurrency_id=cryptocurrency_id).order_by('current_time')
		headers = {
		'Accepts': 'application/json',
		'X-CMC_PRO_API_KEY': '4d958451-c172-4363-a441-d13e8c9d093f',
		}
		params = {
			'symbol' : Cryptocurrency.objects.get(id=cryptocurrency_id).symbol,
			'convert' : 'USD'
		}
		url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest'
		jsonData = requests.get(url, params=params, headers=headers).json()
		labels = []
		data = []

		for ct in cryptocurrency:
			labels.append(ct.current_time.strftime("%Y-%m-%d %H:%M"))
			data.append(ct.current_price)
		data = json.dumps(data)

		context = {
			'labels': json.dumps(labels),
			'data': data,
			'name':Cryptocurrency.objects.get(id = cryptocurrency_id).name,
			'jsonData':jsonData['data'][Cryptocurrency.objects.get(id=cryptocurrency_id).symbol],
			'news': Post.objects.filter(title__contains = Cryptocurrency.objects.get(id=cryptocurrency_id).name)
			}
		return render(request, 'crypto/detail.html', context)
	
class AddPostView(LoginRequiredMixin, View):
	def post(self, request):
		form = PostForm(request.POST)
		if form.is_valid():
			form.save()
		context = {'form':form}
		return redirect('crypto:index')
	def get(self, request):
		form = PostForm()
		context = {'form':form}
		return render(request, 'crypto/add_post.html', context)

class AddCommentView(View):
	def post(self, request,post_id):
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = Comment(name=request.POST.get('name'), body=request.POST.get('body'), post_id=post_id)
			comment.save()
		context = {'form':form}
		return HttpResponseRedirect(reverse('crypto:news_detail', args=[str(post_id)]))
	def get(self, request, post_id):
		form = CommentForm()
		context = {'form':form}
		return render(request, 'crypto/add_comment.html', context)

class PostView(View):
	def get(self, request):
		news = Post.objects.all()
		context = {'news':news}
		return render(request, 'crypto/news.html', context)

class PostDetail(View):
	def get(self, request, post_id):
		news = Post.objects.get(id=post_id)
		liked = False
		if news.likes.filter(id=self.request.user.id).exists():
			liked = True
		context = {
		'news':news,
		'comments':  Comment.objects.filter(post=news),
		'liked':liked
		}
		return render(request, 'crypto/news_detail.html', context)


def LikeView(request,pk):
		user = request.user
		if request.method == 'POST':
			post_id = request.POST['post_id']
			post = get_object_or_404(Post, id=post_id)
			liked = False
			if post.likes.filter(id=request.user.id).exists():
				post.likes.remove(request.user)
				liked = False
			else:
				post.likes.add(request.user)
				post.likes.set = True
		context = {
					'liked':post.likes.filter(id=request.user.id).exists(),
					'total_likes': post.total_likes
					}
		return JsonResponse({'liked':post.likes.filter(id=request.user.id).exists()})


def FavCoinView(request,pk):
		crypto = get_object_or_404(Cryptocurrency, id=request.POST.get('Cryptocurrency_id'))
		liked = False
		if Fav.objects.filter(cryptocurrency_id=crypto.id).exists():
			Fav.objects.filter(cryptocurrency_id=crypto.id).delete()
			liked = False
		else:
			fav = Fav(user=request.user, cryptocurrency_id=crypto.id )
			fav.save()
		coins = Cryptocurrency.objects.all()

		return HttpResponseRedirect(reverse('crypto:index'))


class DeletePostView(LoginRequiredMixin, View):
	def get(self, request, post_id):
		post = Post.objects.get(id=post_id)
		if post.author != request.user:
			raise Http404
		post.delete()
		return HttpResponseRedirect(reverse('crypto:index'))

class EditPostView(LoginRequiredMixin, View):
	def get(self, request, post_id):
		post = Post.objects.get(id=post_id)
		form = PostForm(instance = post)
		if post.author != request.user:
			raise Http404
		context = {'form':form}
		return render(request, 'crypto/edit_post.html', context)

	def post(self, request, post_id):
		form = PostForm(request.POST)
		if form.is_valid():
			post = Post.objects.get(id=post_id)
			if post.author != request.user:
				raise Http404
			post.delete()
			form.save()
		context = {'form':form}
		return redirect('crypto:index')

class ExchangeView(LoginRequiredMixin, View):
	def get(self, request):
		user_entities = Entity.objects.filter(user=request.user)
		total = 0
		for entity in user_entities:
			total += entity.cryptocurrency.price * entity.amount
		context = {
			'user_entities':user_entities,
			'total':total,
			'crypto_list': Cryptocurrency.objects.all()
		}
		return render(request, 'crypto/exchange.html',context )
	def post(self, request):
		user_entities = Entity.objects.filter(user=request.user)
		return render(request, 'crypto/exchange.html', {'user_entities':user_entities})

class BuyCryptoView(LoginRequiredMixin, View):
	def get(self, request):
			amount = request.GET['amount']
			crypto = Cryptocurrency.objects.get(id=request.GET['cryptos'])
			total=float(crypto.price)*float(amount)
			if Entity.objects.filter(cryptocurrency_id=crypto.id,user=request.user).exists():
				entity = Entity.objects.filter(cryptocurrency_id=crypto.id,user=request.user)
				entity2 = Entity.objects.get(cryptocurrency_id=crypto.id,user=request.user)
				entity.update(total=total+entity2.total,amount=float(amount)+entity2.amount)
				return redirect('crypto:exchange')
			else:
				entity = Entity(user=request.user, cryptocurrency=crypto, amount=amount, total=total)
				entity.save()
				print(entity.cryptocurrency.name,"BOUGHT")
				user_entities = Entity.objects.filter(user=request.user)
				return redirect('crypto:exchange')

class SellCryptoView(LoginRequiredMixin, View):
	def get(self, request):
			amount = request.GET['amount']
			crypto = Cryptocurrency.objects.get(id=request.GET['cryptos'])
			entity = Entity.objects.get(cryptocurrency_id=crypto.id,user=request.user)
			entity1 = Entity.objects.filter(cryptocurrency_id=crypto.id,user=request.user)
			if float(amount) < entity.amount:
				new_amount = entity.amount-float(amount)
				new_total = new_amount*crypto.price
				entity1.update(amount=new_amount,total=new_total)
			elif float(amount) == entity.amount:
				entity1.delete()

app/code/crypto/templates/crypto/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Site Metas -->
    <title> Exchange Currency</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="#" type="image/x-icon" />
    <link rel="apple-touch-icon" href="#" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'crypto/css/bootstrap.min.css' %}" />
    <!-- Pogo Slider CSS -->
    <link rel="stylesheet" href="{% static 'crypto/css/pogo-slider.min.css' %}" />
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'crypto/css/style.css' %}?v5" />
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'crypto/css/responsive.css' %}?v2" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'crypto/css/custom.css' %}" />
    <link rel="stylesheet" href="{% static 'crypto/css/font-awesome.min.css' %}" />

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="home" data-spy="scroll" data-target="#navbar-wd" data-offset="98">

    <!-- LOADER -->
    <div id="preloader">
        <div class="loader">
            <img src="{% static 'crypto/images/loader.gif' %}" alt="#" />
        </div>
    </div>
    <!-- end loader -->
    <!-- END LOADER -->

    <!-- Start header -->
    <header class="top-header">

<div class="top-menu">
 {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user"></i>
                            {{ user.first_name }} 
                            {{ user.last_name }}
                          </a>
                         <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'members:edit_profile' %}">Edit Settings</a>
                            <a class="dropdown-item" href="{% url 'crypto:add_post' %}">Add Post</a>
                            {% if user.profile.id %}
                              <a class="dropdown-item" href="{% url 'members:edit_profile_page' user.profile.id %}">Edit Profile Page</a>
                              <a class="dropdown-item" href="{% url 'members:show_profile_page' user.profile.id %}">Show Profile Page</a>           
                            {% else %}  
                              <a class="dropdown-item" href="{% url 'members:create_profile_page' %}">Create Profile Page</a>  
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'members:logoutPage' %}">Logout</a>
                          </div>
                        </li>
                        {% else %}

                          <a class="top-right-bt" href="{% url 'members:register' %}"> <i class="fa fa-plus"> </i> Register</a>
                          |
                          <a class="top-right-bt"  href="{% url 'members:loginPage' %}"><i class="fa fa-sign-in"> </i> Login</a>
                {% endif %}

</div> 

        <div class="header_top">
            
            <div class="container">
                <div class="row">
                    <div class="logo_section">
                        <a class="navbar-brand" href="{% url 'crypto:index' %}"><img src="{% static 'crypto/images/logo.png' %}" alt="image"></a>
                    </div>
                </div>
            </div>
        
        </div>
        <div class="header_bottom">
          <div class="container">


            <div class="col-sm-12">
                <div class="menu_orange_section" style="background: #ff880e;">
                   <nav class="navbar header-nav navbar-expand-lg"> 
                     <div class="menu_section">
                       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-wd" aria-controls="navbar-wd" aria-expanded="false" aria-label="Toggle navigation">
                          <span></span>
                          <span></span>
                          <span></span>
                      </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbar-wd">
                      <ul class="navbar-nav">
                        <li><a class="nav-link active" href="{% url 'crypto:index' %}">Home</a></li>
                        <li><a class="nav-link" href="{% url 'crypto:exchange' %}">Exchange</a></li>
                        <li><a class="nav-link" href="{% url 'crypto:view_post' %}">News</a></li>
                      </ul>
                  </div>
                
                 </nav>
                 <div class="search-box">
                    <form class="form-inline my-2 my-lg-0" method=GET action ="{% url 'crypto:search-cryptos' %}" >
                      {% csrf_token %}
                      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name = "searched">
                      <button class="btn btn-outline-warning" type="submit">Search</button>
                    </form>
                </div> 
                </div>
            </div>

          </div>
        </div>
        
    </header>
    <!-- End header -->
    {% block content %}
    {% endblock %}
    
    <!-- Start Footer -->
    <footer class="footer-box">
        <div class="container">
            <div class="row">
               <div class="col-md-12 white_fonts">
                    <div class="row">
                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <div class="full">
                                <img class="img-responsive" src="{% static 'crypto/images/footer_logo.png' %}" alt="#" />
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <div class="full">
                                <h3>Quick Links</h3>
                            </div>
                            <div class="full">
                                <ul class="menu_footer">
                                    <li><a href="{% url 'crypto:index' %}">> Home </a></li>
                                    <li><a href="{% url 'crypto:exchange' %}">> Exchange </a></li>
                                    <li><a href="{% url 'crypto:view_post' %}">> News </a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <div class="full">
                                <div class="footer_blog full white_fonts">
                         </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6 col-lg-3">
                            <div class="full">
                                <div class="footer_blog full white_fonts">
                             <h3>Contact us</h3>
                             <ul class="full">
                               <li><img src="{% static 'crypto/images/i5.png' %}"><span>Ankara<br>Turkey</span></li>
                               <li><img src="{% static 'crypto/images/i6.png' %}"><span>demo@gmail.com</span></li>
                               <li><img src="{% static 'crypto/images/i7.png' %}"><span>+12586954775</span></li>
                             </ul>
                         </div>
                            </div>
                        </div>
					</div>
                </div>
			 </div>
        </div>
    </footer>
    <!-- End Footer -->

    <a href="#" id="scroll-to-top" class="hvr-radial-out"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="{% static 'crypto/js/jquery.min.js' %}"></script>
	<script src="{% static 'crypto/js/popper.min.js' %}"></script>
    <script src="{% static 'crypto/js/bootstrap.min.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'crypto/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'crypto/js/jquery.pogo-slider.min.js' %}"></script>
    <script src="{% static 'crypto/js/slider-index.js' %}"></script>
    <script src="{% static 'crypto/js/smoothscroll.js' %}"></script>
    <script src="{% static 'crypto/js/form-validator.min.js' %}"></script>
    <script src="{% static 'crypto/js/contact-form-script.js' %}"></script>
    <script src="{% static 'crypto/js/isotope.min.js' %}"></script>
    <script src="{% static 'crypto/js/images-loded.min.js' %}"></script>
    <script src="{% static 'crypto/js/custom.js' %}"></script>
	<script>
	/* counter js */

(function ($) {
	$.fn.countTo = function (options) {
		options = options || {};
		
		return $(this).each(function () {
			// set options for current element
			var settings = $.extend({}, $.fn.countTo.defaults, {
				from:            $(this).data('from'),
				to:              $(this).data('to'),
				speed:           $(this).data('speed'),
				refreshInterval: $(this).data('refresh-interval'),
				decimals:        $(this).data('decimals')
			}, options);
			
			// how many times to update the value, and how much to increment the value on each update
			var loops = Math.ceil(settings.speed / settings.refreshInterval),
				increment = (settings.to - settings.from) / loops;
			
			// references & variables that will change with each update
			var self = this,
				$self = $(this),
				loopCount = 0,
				value = settings.from,
				data = $self.data('countTo') || {};
			
			$self.data('countTo', data);
			
			// if an existing interval can be found, clear it first
			if (data.interval) {
				clearInterval(data.interval);
			}
			data.interval = setInterval(updateTimer, settings.refreshInterval);
			
			// initialize the element with the starting value
			render(value);
			
			function updateTimer() {
				value += increment;
				loopCount++;
				
				render(value);
				
				if (typeof(settings.onUpdate) == 'function') {
					settings.onUpdate.call(self, value);
				}
				
				if (loopCount >= loops) {
					// remove the interval
					$self.removeData('countTo');
					clearInterval(data.interval);
					value = settings.to;
					
					if (typeof(settings.onComplete) == 'function') {
						settings.onComplete.call(self, value);
					}
				}
			}
			
			function render(value) {
				var formattedValue = settings.formatter.call(self, value, settings);
				$self.html(formattedValue);
			}
		});
	};
	
	$.fn.countTo.defaults = {
		from: 0,               // the number the element should start at
		to: 0,                 // the number the element should end at
		speed: 1000,           // how long it should take to count between the target numbers
		refreshInterval: 100,  // how often the element should be updated
		decimals: 0,           // the number of decimal places to show
		formatter: formatter,  // handler for formatting the value before rendering
		onUpdate: null,        // callback method for every time the element is updated
		onComplete: null       // callback method for when the element finishes updating
	};
	
	function formatter(value, settings) {
		return value.toFixed(settings.decimals);
	}
}(jQuery));

jQuery(function ($) {
  // custom formatting example
  $('.count-number').data('countToOptions', {
	formatter: function (value, options) {
	  return value.toFixed(options.decimals).replace(/\B(?=(?:\d{3})+(?!\d))/g, ',');
	}
  });
  
  // start all the timers
  $('.timer').each(count);  
  
  function count(options) {
	var $this = $(this);
	options = $.extend({}, options || {}, $this.data('countToOptions') || {});
	$this.countTo(options);
  }
});
	</script>
    {% block js %}
    {% endblock js %}
</body>

</html>